### ISSUE TITLE
tagged releases

### ISSUE THREAD

**Issue by TeddyDD** [skeeto/passphrase2pgp#1]
Could you tag releases please? They would be very useful for packaging purposes.

**Comment by skeeto** [comment]
I've been meaning to create a tag, but hesitated since I'm still 
occasionally breaking things (such as -e no longer being short for 
--pinentry) as I feel out the UI. Plus I didn't think anyone else really 
cared that much yet!

I just tagged v0.1.0 (at e225c96). After I've spent more time dogfooding 
it, and I think the UI is just right, I'll tag v1.0.0. I'm stilling 
thinking about making --encrypt (-e) the default, for example. I don't 
expect the key generation algorithm to change, so keys generated now 
should be stable going forward.

**Comment by TeddyDD** [comment]
That will do, thank you :)
